config/routes.rb
PrivateInvite::Application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  match '/about', to: 'static_pages#about' ,via:'get'
  match '/contact', to: 'static_pages#contact', via:'get'
  match '/events', to: 'static_pages#events', via:'get'
  match '/events/nin', to: 'static_pages#nin', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users/invitations.rb
class Users::InvitationsController < Devise::InvitationsController
  def update
    if this
      redirect_to root_path
    else
      super
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="robots" content="noindex">
  <title>Private Invite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <header class="navbar navbar-fixed-top">
            <div class= "navbar-inner">
                <div class="container">

                    <%= link_to "Private Invite", root_path, id: "logo" %>
                 <!--   <%= link_to image_tag("PIKEYLargeLogo.png",size:"75x32", alt: "Private Invite"), root_path, id:"logo" %>-->
                    <nav>
                        <ul class="nav pull-right">
                            <li><%= link_to "Home", root_path %></li>
                            <li><%= link_to "About", about_path %></li>
                            <li><%= link_to "Contact", contact_path  %></li>
                            <% if user_signed_in? %>
                            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
                            <% else %>
                            <li><%= link_to "Sign In", new_user_session_path  %></li>
                            <li><%= link_to "Register", new_user_registration_path  %></li>
                            <% end %>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div class="container">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
        </div>
    </body>
</html>

app/views/static_pages/about.html.erb
<div class= "center hero-unit">
    <%= link_to image_tag("PIKEYLargeLogo.png",size:"300x131", alt: "Private Invite"), 'http://privateinvite.io/' %>
    <!--<h1>Private Invite</h1>-->
    <h2>Coming Soon</h2>

</div>

app/views/static_pages/contact.html.erb
<div class= "center hero-unit">
    <%= link_to image_tag("PIKEYLargeLogo.png",size:"300x131", alt: "Private Invite"), 'http://privateinvite.io/' %>
    <!--<h1>Private Invite</h1>-->
    <h2>Coming Soon</h2>

</div>

app/views/static_pages/events.html.erb
<div class= "center hero-unit">
    <div class="well">
    <!--<h2>Naughty in N'awlins</h2>
    <h3>Aug 6-10, 2014</h3>-->
    <table class="table table-stripped">
              <thead>
                <tr>
                    <h1>Upcoming Events</h1>
                </tr>

              </thead>

              <tbody>
                <tr>

                  <td><a href="https://secureregistrationonline.com/new_nin/signup.php?affiliateId=1889" target="_blank"><img src="https://secureregistrationonline.com/images/nin_250x55.jpg" alt="Naughty in N'awlins" border="0" target="_blank"></a>
                  </td>
                  <td><%= link_to ("More Info"), "https://secureregistrationonline.com/new_nin/signup.php?affiliateId=1889", class: "btn btn-large btn-primary", target: '_blank' %>
                  </td>
                  <td><%= link_to ("Sign Up Now"), "https://secureregistrationonline.com/new_nin/signup.php?affiliateId=1889", class: "btn btn-large btn-primary", target: '_blank' %>
                  </td>
              </tr>
              </tbody>
            </table>
        </div>
</div>

app/views/static_pages/home.html.erb
<div class= "center hero-unit">
    <% if user_signed_in? %>
    <%= link_to image_tag("PIKEYLargeLogo.png",size:"300x131", alt: "Private Invite"), root_path %>
    <br>
    <%= link_to "Send An Invite!", new_user_invitation_path, class: "btn btn-large btn-primary" %>

    <% else %>
    <%= link_to image_tag("PIKEYLargeLogo.png",size:"300x131", alt: "Private Invite"), root_path %>
    <!--<h1>Private Invite</h1>-->
    <h2>Invite Only - Still in Beta</h2>

    <%= link_to "Sign In", new_user_session_path, class: "btn btn-large btn-primary" %>
    <% end %>
</div>

app/views/static_pages/nin.html.erb
<div>
    <iframe src="https://secureregistrationonline.com/new_nin/signup.php?affiliateId=1889&c=1" name="targetframe" width="100%" height ="4600px" allowTransparency="true" scrolling="no"  frameborder="0" >
</div>

app/views/users/invitations/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>